const Images = {
    homeIcon: require("../images/home.png"),
    shoppingBagIcon: require("../images/bag.png"),
    insuranceIcon: require("../images/insurance.png"),
    rupeeIcon: require("../images/rupee.png"),
    transactionIcon: require("../images/transaction.png"),
    userIcon: require("../images/man.png"),
    flagIcon: require("../images/flag.png"),
    downIcon: require("../images/caret-down.png"),
    qrCodeIcon: require("../images/qr-code.png"),
    bellIcon: require("../images/bell.png"),
    helpIcon: require("../images/question.png"),
    logoIcon: require("../images/logo.png"),
    bannerImg: require("../images/banner.png"),
    usersIcon: require("../images/user.png"),
    bankIcon: require("../images/bank.png"),
    bank2Icon: require("../images/bank2.png"),
    selfIcon: require("../images/self.png"),
    walletIcon: require("../images/wallet.png"),
    giftIcon: require("../images/gift.png"),
    referIcon: require("../images/marketing.png"),
    mobileIcon: require("../images/mobile.png"),
    creditcardIcon: require("../images/credit-card.png"),
    lightIcon: require("../images/light.png"),
    dthIcon: require("../images/dth.png"),
    gasIcon: require("../images/gas.png"),
  };
  
  export default Images;
  